version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2022:2022
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "adployee.js"]
